// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace chatbox.Models;

public partial class Chatdata
{
    public int ChatIdPk { get; set; }

    public int SenderIdFk { get; set; }

    public int ReceiverIdFk { get; set; }

    public DateTime LastMessageTime { get; set; }

    public virtual ICollection<Messagedata> Messagedata { get; set; } = new List<Messagedata>();

    public virtual Userdata ReceiverIdFkNavigation { get; set; }

    public virtual Userdata SenderIdFkNavigation { get; set; }
}