// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace chatbox.Models;

public partial class Messagedata
{
    public int MessageIdPk { get; set; }

    public int ChatIdFk { get; set; }

    public int SenderIdFk { get; set; }

    public string Message { get; set; }

    public DateTime MessageTime { get; set; }

    public bool? MessageSeen { get; set; }

    public int? ReceiverIdFk { get; set; }

    public virtual Chatdata ChatIdFkNavigation { get; set; }

    public virtual Userdata SenderIdFkNavigation { get; set; }
}