// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace chatbox.Models;

public partial class Userdata
{
    public int UserIdPk { get; set; }

    public string UserName { get; set; }

    public string PhoneNoUk { get; set; }

    public string Email { get; set; }

    public string LoginIdUk { get; set; }

    public string Password { get; set; }

    public virtual ICollection<Chatdata> ChatdatumReceiverIdFkNavigations { get; set; } = new List<Chatdata>();

    public virtual ICollection<Chatdata> ChatdatumSenderIdFkNavigations { get; set; } = new List<Chatdata>();

    public virtual ICollection<Messagedata> Messagedata { get; set; } = new List<Messagedata>();
}